### PR TITLE
Layout changes

### PR DESCRIPTION
**Pull request by jennyhelyanwe**
Hi @alan-wu here's what I've changed:
1. Replaced big round buttons for diseases with tab form instead, to make progressing through the app more intuitive (this was Megan's suggestion :) 

2. Update 'check your understanding' and 'click to close' buttons

### CODE REVIEW

**Comment by alan-wu** [comment]
Looks nice, one question is the home button necessary?

**Comment by jennyhelyanwe** [comment]
Hey, yup so the home button is supposed to direct us back to the main menu from which the other content from AUT and stuff would be available.

**Comment by alan-wu** [comment]
Fair enough, by the way Healthy is misspelled on the button.

**Comment by jennyhelyanwe** [comment]
Oops, dang it haha I'll create another pull request.

**Pull request merged**
