### PR TITLE
About us page, home button, and layout changes. 

### PR DESCRIPTION
**Pull request by jennyhelyanwe**
hi @alan-wu 

1) About us page setup
2) Layout changes
3) Wording changes. 

Cheers,
J

### CODE REVIEW

**Comment by jennyhelyanwe** [comment]
Would be great if you could update the online version if this merges fine, then I'll send around an email to everyone to get feedback! Many thanks!

**Comment by jennyhelyanwe** [comment]
Hold up on this, sorry, bug fix coming!

**Comment by jennyhelyanwe** [comment]
Hi @alan-wu sorry about the flood of changes, I've also incorporated Prasad's changes for the home button. Could we pull this in?

**Comment by alan-wu** [comment]
I will pull this in now.

**Pull request merged**
